name: 'make github app token'
description: 'Greet someone and record the time'
inputs:
  appId:
    description: 'AppId'
    required: true
  PK:
    description: 'PEM'
    required: true
  installationId:
    description: 'instllationId'
    required: true
outputs:
  token: 
    description: 'Github App Auth Token'
runs:
  using: node16
  main: dist/index.js
